### ISSUE TITLE
PHP-FPM monitor needs UNIX socket support

### ISSUE THREAD

**Issue by sunsongxp** [wiredcraft-ops/role-wcl-zabbix-scripts#6]
- Need to support UNIX socket instead of TCP only

**Comment by sunsongxp** [comment]
@zbal https://github.com/wiredcraft-ops/role-wcl-zabbix-scripts/pull/7

**Comment by zbal** [comment]
You may want to specify some defaults to your ansible values; if we set the php-fpm attibute in a role for a socket - I would doubt we input blank values like:

```
---
- hosts: all
  roles:
    - role: wcl-zabbix-scripts
      zabbix_php_fpm:
        host: ''
        port: ''
        socket: '/some/socket'

--- most likely

- hosts: all
  roles:
    - role: wcl-zabbix-scripts
      zabbix_php_fpm:
        socket: '/some/socket'
```

In the latter case, the template script will probably fail because it can't find `{{ zabbix_php_fpm.host }}` - you may want to replace it by `{{ zabbix_php_fpm.host | default('') }}` or something like that.

Also - side note - `@zbal #7` is not enough as a comment and I won't be checking next time if I lack info. 
Same note for the PR - no description at all is not acceptable either.
